min_area_sqm: 50
layouts:
  - 2LDK
  - 3DK
targets:
  - name: 大島四丁目
    url: https://www.ur-net.go.jp/chintai/kanto/tokyo/20_1780.html
    room_url: https://www.ur-net.go.jp/chintai/kanto/tokyo/20_1780_room.html
  - name: 大島六丁目
    url: https://www.ur-net.go.jp/chintai/kanto/tokyo/20_1920.html
    room_url: https://www.ur-net.go.jp/chintai/kanto/tokyo/20_1920_room.html
